# Generated by Django 5.0.4 on 2024-04-16 13:04

import theatre.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0003_performance_reservation_ticket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='play',
            name='image',
            field=models.ImageField(
                null=True,
                upload_to=theatre.models.play_image_path),
        ),
    ]
