# Generated by Django 5.0.4 on 2024-04-16 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0004_alter_reservation_options_play_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play',
            name='actors',
            field=models.ManyToManyField(blank=True, to='theatre.actor'),
        ),
        migrations.AlterField(
            model_name='play',
            name='genres',
            field=models.ManyToManyField(blank=True, to='theatre.genre'),
        ),
    ]
